name = "omar-chatbot-worker"
main = "src/index.js"
compatibility_date = "2024-09-01"

[ai]
binding = "AI"

[vars]
AI_MODEL = "@cf/meta/llama-3.1-8b-instruct"

[[env.production]]
vars = { ENVIRONMENT = "production" }
